---
apiVersion: v1
kind: Namespace
metadata:
  name: website-test  # Maybe terraform to make this dynamic for multiple envs.
  labels:
    env: test
    project: website
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: website-test
  labels:
    env: test
    project: website
    name: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      env: test
      project: website
      name: ui
  template:
    metadata:
      name: ui
      namespace: website-test
      labels:
        env: test
        project: website
        name: ui
    spec:
      containers:
        - image: medkha/website:1.0.2
          name: ui
          # Experimenting, not sure yet the optimal values.
          resources:
            requests:
              memory: 20Mi
            limits:
              memory: 50Mi
---
# the autoscaler is not needed on
# the test environment in the future
# When we have the project deployed in staging and prod.
# For now the test env is the prod.
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ui-hpa
  namespace: website-test
  labels:
    env: test
    project: website
    name: ui
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ui
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          averageUtilization: 80
          type: Utilization
---
apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: website-test
  labels:
    env: test
    project: website
    name: ui
spec:
  selector:
    name: ui
    project: website
    env: test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
